#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : zope.configuration
Version  : 4.3.0
Release  : 18
URL      : https://files.pythonhosted.org/packages/5c/59/46de8bdebaed1dd10bdfc2f089509994d2acf4d9860e3422219077b7247f/zope.configuration-4.3.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/5c/59/46de8bdebaed1dd10bdfc2f089509994d2acf4d9860e3422219077b7247f/zope.configuration-4.3.0.tar.gz
Summary  : Zope Configuration Markup Language (ZCML)
Group    : Development/Tools
License  : ZPL-2.1
Requires: zope.configuration-python3
Requires: zope.configuration-license
Requires: zope.configuration-python
Requires: Sphinx
Requires: setuptools
Requires: zope.i18nmessageid
Requires: zope.interface
Requires: zope.schema
Requires: zope.testing
Requires: zope.testrunner
BuildRequires : buildreq-distutils3
BuildRequires : setuptools
BuildRequires : zope.i18nmessageid
BuildRequires : zope.interface
BuildRequires : zope.schema

%description
======================

%package license
Summary: license components for the zope.configuration package.
Group: Default

%description license
license components for the zope.configuration package.


%package python
Summary: python components for the zope.configuration package.
Group: Default
Requires: zope.configuration-python3 = %{version}-%{release}

%description python
python components for the zope.configuration package.


%package python3
Summary: python3 components for the zope.configuration package.
Group: Default
Requires: python3-core

%description python3
python3 components for the zope.configuration package.


%prep
%setup -q -n zope.configuration-4.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1538410053
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check || :
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/zope.configuration
cp LICENSE.txt %{buildroot}/usr/share/doc/zope.configuration/LICENSE.txt
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/doc/zope.configuration/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
