#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : zope.configuration
Version  : 4.3.1
Release  : 21
URL      : https://files.pythonhosted.org/packages/96/0c/a2a18c2846639f4a4adcc6bed1584555b08132b4aaf4b7972653c5051ae0/zope.configuration-4.3.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/96/0c/a2a18c2846639f4a4adcc6bed1584555b08132b4aaf4b7972653c5051ae0/zope.configuration-4.3.1.tar.gz
Summary  : Zope Configuration Markup Language (ZCML)
Group    : Development/Tools
License  : ZPL-2.1
Requires: zope.configuration-license = %{version}-%{release}
Requires: zope.configuration-python = %{version}-%{release}
Requires: zope.configuration-python3 = %{version}-%{release}
Requires: setuptools
Requires: zope.i18nmessageid
Requires: zope.interface
Requires: zope.schema
BuildRequires : buildreq-distutils3
BuildRequires : setuptools
BuildRequires : zope.i18nmessageid
BuildRequires : zope.interface
BuildRequires : zope.schema

%description
``zope.configuration``
======================
.. image:: https://img.shields.io/pypi/v/zope.configuration.svg
:target: https://pypi.python.org/pypi/zope.configuration/
:alt: Latest Version

%package license
Summary: license components for the zope.configuration package.
Group: Default

%description license
license components for the zope.configuration package.


%package python
Summary: python components for the zope.configuration package.
Group: Default
Requires: zope.configuration-python3 = %{version}-%{release}

%description python
python components for the zope.configuration package.


%package python3
Summary: python3 components for the zope.configuration package.
Group: Default
Requires: python3-core

%description python3
python3 components for the zope.configuration package.


%prep
%setup -q -n zope.configuration-4.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549996025
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check || :
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/zope.configuration
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/zope.configuration/LICENSE.txt
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/zope.configuration/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
